// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/approvals" | "/calendar" | "/campaigns" | "/campaigns/[campaignId]" | "/content" | "/integrations" | "/marketing-planner" | "/operations" | "/performance" | "/post-creator" | "/reporting" | "/revenue-modeling" | "/settings" | "/web-analytics" | "/weekly-performance"
type AppRouteHandlerRoutes = "/api/approvals" | "/api/approvals/[approvalId]" | "/api/assets" | "/api/blog-posts" | "/api/campaigns" | "/api/campaigns/[campaignId]" | "/api/client-memberships" | "/api/client-memberships/[membershipId]" | "/api/clients" | "/api/google-analytics" | "/api/google-analytics/sync" | "/api/integrations" | "/api/integrations/connections/[connectionId]" | "/api/integrations/connections/[connectionId]/check" | "/api/integrations/sync-jobs/[jobId]" | "/api/integrations/sync-jobs/[jobId]/run" | "/api/meta-suite" | "/api/meta-suite/callback" | "/api/meta-suite/connect" | "/api/meta-suite/select" | "/api/meta-suite/sync" | "/api/operations" | "/api/operations/tasks" | "/api/operations/tasks/[taskId]" | "/api/planner-items" | "/api/planner-items/[itemId]" | "/api/posts" | "/api/posts/[postId]" | "/api/publishing" | "/api/publishing/[jobId]" | "/api/weekly-metrics" | "/api/weekly-metrics/[metricId]" | "/api/workspace/members" | "/api/workspace/members/[memberId]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/approvals": {}
  "/api/approvals/[approvalId]": { "approvalId": string; }
  "/api/assets": {}
  "/api/blog-posts": {}
  "/api/campaigns": {}
  "/api/campaigns/[campaignId]": { "campaignId": string; }
  "/api/client-memberships": {}
  "/api/client-memberships/[membershipId]": { "membershipId": string; }
  "/api/clients": {}
  "/api/google-analytics": {}
  "/api/google-analytics/sync": {}
  "/api/integrations": {}
  "/api/integrations/connections/[connectionId]": { "connectionId": string; }
  "/api/integrations/connections/[connectionId]/check": { "connectionId": string; }
  "/api/integrations/sync-jobs/[jobId]": { "jobId": string; }
  "/api/integrations/sync-jobs/[jobId]/run": { "jobId": string; }
  "/api/meta-suite": {}
  "/api/meta-suite/callback": {}
  "/api/meta-suite/connect": {}
  "/api/meta-suite/select": {}
  "/api/meta-suite/sync": {}
  "/api/operations": {}
  "/api/operations/tasks": {}
  "/api/operations/tasks/[taskId]": { "taskId": string; }
  "/api/planner-items": {}
  "/api/planner-items/[itemId]": { "itemId": string; }
  "/api/posts": {}
  "/api/posts/[postId]": { "postId": string; }
  "/api/publishing": {}
  "/api/publishing/[jobId]": { "jobId": string; }
  "/api/weekly-metrics": {}
  "/api/weekly-metrics/[metricId]": { "metricId": string; }
  "/api/workspace/members": {}
  "/api/workspace/members/[memberId]": { "memberId": string; }
  "/approvals": {}
  "/calendar": {}
  "/campaigns": {}
  "/campaigns/[campaignId]": { "campaignId": string; }
  "/content": {}
  "/integrations": {}
  "/marketing-planner": {}
  "/operations": {}
  "/performance": {}
  "/post-creator": {}
  "/reporting": {}
  "/revenue-modeling": {}
  "/settings": {}
  "/web-analytics": {}
  "/weekly-performance": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
