// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(dashboard)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/approvals">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/campaigns/[campaignId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns/[campaignId]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/campaigns/[campaignId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/content">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/marketing-planner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing-planner">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/marketing-planner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/post-creator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/post-creator">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/post-creator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/reporting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reporting">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/reporting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/revenue-modeling/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/revenue-modeling">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/revenue-modeling/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/web-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-analytics">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/web-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/weekly-performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/weekly-performance">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/weekly-performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/approvals/[approvalId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/approvals/[approvalId]">> = Specific
  const handler = {} as typeof import("../../app/api/approvals/[approvalId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/approvals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/approvals">> = Specific
  const handler = {} as typeof import("../../app/api/approvals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets">> = Specific
  const handler = {} as typeof import("../../app/api/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog-posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog-posts">> = Specific
  const handler = {} as typeof import("../../app/api/blog-posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/[campaignId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/[campaignId]">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/[campaignId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/client-memberships/[membershipId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client-memberships/[membershipId]">> = Specific
  const handler = {} as typeof import("../../app/api/client-memberships/[membershipId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/client-memberships/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/client-memberships">> = Specific
  const handler = {} as typeof import("../../app/api/client-memberships/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients">> = Specific
  const handler = {} as typeof import("../../app/api/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/google-analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google-analytics">> = Specific
  const handler = {} as typeof import("../../app/api/google-analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/google-analytics/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google-analytics/sync">> = Specific
  const handler = {} as typeof import("../../app/api/google-analytics/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/connections/[connectionId]/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/connections/[connectionId]/check">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/connections/[connectionId]/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/connections/[connectionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/connections/[connectionId]">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/connections/[connectionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/sync-jobs/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/sync-jobs/[jobId]">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/sync-jobs/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/sync-jobs/[jobId]/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/sync-jobs/[jobId]/run">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/sync-jobs/[jobId]/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-suite/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-suite/callback">> = Specific
  const handler = {} as typeof import("../../app/api/meta-suite/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-suite/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-suite/connect">> = Specific
  const handler = {} as typeof import("../../app/api/meta-suite/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-suite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-suite">> = Specific
  const handler = {} as typeof import("../../app/api/meta-suite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-suite/select/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-suite/select">> = Specific
  const handler = {} as typeof import("../../app/api/meta-suite/select/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-suite/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-suite/sync">> = Specific
  const handler = {} as typeof import("../../app/api/meta-suite/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operations">> = Specific
  const handler = {} as typeof import("../../app/api/operations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operations/tasks/[taskId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operations/tasks/[taskId]">> = Specific
  const handler = {} as typeof import("../../app/api/operations/tasks/[taskId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operations/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operations/tasks">> = Specific
  const handler = {} as typeof import("../../app/api/operations/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner-items/[itemId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner-items/[itemId]">> = Specific
  const handler = {} as typeof import("../../app/api/planner-items/[itemId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/planner-items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planner-items">> = Specific
  const handler = {} as typeof import("../../app/api/planner-items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/posts/[postId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[postId]">> = Specific
  const handler = {} as typeof import("../../app/api/posts/[postId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts">> = Specific
  const handler = {} as typeof import("../../app/api/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/publishing/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/publishing/[jobId]">> = Specific
  const handler = {} as typeof import("../../app/api/publishing/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/publishing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/publishing">> = Specific
  const handler = {} as typeof import("../../app/api/publishing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/weekly-metrics/[metricId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weekly-metrics/[metricId]">> = Specific
  const handler = {} as typeof import("../../app/api/weekly-metrics/[metricId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/weekly-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weekly-metrics">> = Specific
  const handler = {} as typeof import("../../app/api/weekly-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/members/[memberId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/members/[memberId]">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/members/[memberId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/members">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
